### ISSUE TITLE
后台node+koa2+mysql配置

### ISSUE THREAD

**Issue by WebLeader** [wclimb/video-admin#3]
我配置koa2+mysql数据库的时候，配置好后，启动项目报错

> koa2-blog@1.0.0 dev F:\work\Vue\video-admin-master\Koa2-blog
> supervisor --harmony index

Running node-supervisor with
  program '--harmony index'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node --harmony index'
Watching directory 'F:\work\Vue\video-admin-master\Koa2-blog' for changes.
Press rs for restarting the process.
F:\work\Vue\video-admin-master\Koa2-blog\node_modules\koa-bodyparser\index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\work\Vue\video-admin-master\Koa2-blog\index.js:3:18)
    at Module._compile (module.js:570:32)
Program node --harmony index exited with code 1

**Comment by wclimb** [comment]
@WebLeader node的版本你升级一下吧，不支持async
